#!/bin/sh

export PATH=$PATH:/mnt/nand1-2/bin:/sbin
export LD_LIBRARY_PATH=./

#insmod /usr/fa93_devmem.ko

insmod /usr/board_leds.ko

if [ ! -d /mnt/nuwicam ];then mkdir -p /mnt/nuwicam; fi

echo "Mount APP root F/S"
mount -t jffs2 /dev/mtdblock0 /mnt/nuwicam
if [ -f /mnt/nuwicam/go.sh ]; then
	echo "Run APP"
	/mnt/nuwicam/go.sh &
fi
